import type { EpisodeConfig, Story as StoryType } from '../../types';
import { colors, fonts, inputStyle } from '../../theme';
import { ErrorBanner, PrimaryButton, SecondaryButton, Spinner } from '../ui';

export function Story({
  episodeConfig,
  story,
  storyGenStatus,
  storyGenError,
  isEditingStory,
  toggleEditStory,
  setStoryFull,
  approveStory,
  regenerateStory,
}: {
  episodeConfig: EpisodeConfig;
  story: StoryType | null;
  storyGenStatus: 'idle' | 'generating' | 'ready' | 'error';
  storyGenError: string | null;
  isEditingStory: boolean;
  toggleEditStory: () => void;
  setStoryFull: (v: string) => void;
  approveStory: () => void;
  regenerateStory: () => void;
}) {
  return (
    <div data-screen-label="Story Generation" style={{ maxWidth: 880, margin: '0 auto', padding: '32px 32px 90px' }}>
      <div style={{ marginBottom: 24 }}>
        <div style={{ fontFamily: fonts.display, fontWeight: 800, fontSize: 26, marginBottom: 6 }}>Your episode story</div>
        <div style={{ fontSize: 14, color: colors.muted }}>Generated by Nova's story model from your characters, theme, and idea.</div>
      </div>

      {storyGenStatus === 'generating' && (
        <div style={{ background: 'linear-gradient(180deg,rgba(255,255,255,0.045),rgba(255,255,255,0.015))', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 20, padding: '60px 28px', textAlign: 'center' }}>
          <div style={{ marginBottom: 20 }}>
            <Spinner />
          </div>
          <div style={{ fontFamily: fonts.display, fontWeight: 700, fontSize: 15, marginBottom: 6 }}>Writing your story…</div>
          <div style={{ fontSize: 13, color: colors.muted }}>
            Story generation model is drafting a {episodeConfig.theme} episode for {episodeConfig.duration}.
          </div>
        </div>
      )}

      {storyGenStatus === 'error' && (
        <div style={{ background: 'linear-gradient(180deg,rgba(255,255,255,0.045),rgba(255,255,255,0.015))', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 20, padding: 28 }}>
          <ErrorBanner message={storyGenError || 'Story generation failed.'} onRetry={regenerateStory} />
        </div>
      )}

      {storyGenStatus === 'ready' && story && (
        <div style={{ background: 'linear-gradient(180deg,rgba(255,255,255,0.045),rgba(255,255,255,0.015))', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 20, padding: 30 }}>
          <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, padding: '5px 12px', borderRadius: 999, background: 'rgba(139,92,246,0.15)', fontSize: 11, fontWeight: 700, color: colors.violetSoft, marginBottom: 14 }}>
            STORY MODEL OUTPUT
          </div>
          <div style={{ fontFamily: fonts.display, fontWeight: 800, fontSize: 24, marginBottom: 10 }}>{story.title}</div>
          <div style={{ fontSize: 14, color: colors.bodyText2, fontStyle: 'italic', marginBottom: 20, lineHeight: 1.6 }}>{story.synopsis}</div>

          <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginBottom: 20 }}>
            {story.roleChips.map((rc) => (
              <div key={rc.name} style={{ padding: '6px 12px', borderRadius: 999, background: 'rgba(255,255,255,0.05)', border: '1px solid rgba(255,255,255,0.1)', fontSize: 12, fontWeight: 600 }}>
                {rc.name} <span style={{ color: colors.muted }}>· {rc.role}</span>
              </div>
            ))}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 14, marginBottom: 22 }}>
            <div style={{ background: 'rgba(255,255,255,0.03)', borderRadius: 14, padding: 16 }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: colors.violet, marginBottom: 6 }}>BEGINNING</div>
              <div style={{ fontSize: 13, color: colors.bodyText2, lineHeight: 1.55 }}>{story.beginning}</div>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.03)', borderRadius: 14, padding: 16 }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: colors.pink, marginBottom: 6 }}>MIDDLE</div>
              <div style={{ fontSize: 13, color: colors.bodyText2, lineHeight: 1.55 }}>{story.middle}</div>
            </div>
            <div style={{ background: 'rgba(255,255,255,0.03)', borderRadius: 14, padding: 16 }}>
              <div style={{ fontSize: 11, fontWeight: 700, color: colors.blue, marginBottom: 6 }}>ENDING</div>
              <div style={{ fontSize: 13, color: colors.bodyText2, lineHeight: 1.55 }}>{story.ending}</div>
            </div>
          </div>

          <div style={{ marginBottom: 8, fontSize: 12, fontWeight: 700, color: colors.muted }}>FULL STORY</div>
          {isEditingStory ? (
            <textarea
              value={story.full}
              onChange={(e) => setStoryFull(e.target.value)}
              rows={8}
              style={{ ...inputStyle, padding: 14, borderRadius: 12, border: '1px solid rgba(139,92,246,0.4)', fontSize: 13.5, lineHeight: 1.7, resize: 'vertical' }}
            />
          ) : (
            <div style={{ fontSize: 13.5, color: colors.bodyText, lineHeight: 1.75, whiteSpace: 'pre-line' }}>{story.full}</div>
          )}

          <div style={{ display: 'flex', gap: 12, marginTop: 26, flexWrap: 'wrap' }}>
            <PrimaryButton
              onClick={approveStory}
              style={{ background: 'linear-gradient(135deg,#34D399,#10B981)', color: colors.greenDeep, boxShadow: 'none', padding: '14px 24px', fontSize: 14 }}
            >
              ✓ Approve story
            </PrimaryButton>
            <SecondaryButton onClick={regenerateStory}>Regenerate story</SecondaryButton>
            <SecondaryButton onClick={toggleEditStory}>{isEditingStory ? 'Done editing' : 'Edit story manually'}</SecondaryButton>
          </div>
        </div>
      )}
    </div>
  );
}
